const API_URL='https://script.google.com/macros/s/AKfycbxpX9FNMZZDL72L76vS4keCiWC3xPb79_cMkpcBk0_AqktKHizk7j5A6r53brRN9y9d/exec';
const HOJAS=[{nombre:'TRT',empresa:'TRT',tipo:'COBRADO'},{nombre:'SUR',empresa:'SUR',tipo:'COBRADO'},{nombre:'AVATRT',empresa:'TRT',tipo:'ADEUDO'},{nombre:'AVASUR',empresa:'SUR',tipo:'ADEUDO'}];
const COLORS=['#16a34a','#2563eb','#f59e0b','#dc2626','#7c3aed','#0891b2','#db2777','#475569','#ea580c','#0f766e'];
let allRows=[],currentRows=[],charts={};const $=id=>document.getElementById(id);
const money=n=>Number(n||0).toLocaleString('es-MX',{style:'currency',currency:'MXN'});const num=n=>Number(n||0).toLocaleString('es-MX');
const cleanKey=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const cleanText=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function setStatus(m,t=''){ $('statusBox').textContent=m; $('statusBox').className='status '+t; }
function escapeHtml(v){return String(v??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
function getField(row,names){const keys=Object.keys(row||{});for(const n of names){const k=keys.find(x=>cleanKey(x)===cleanKey(n));if(k&&String(row[k]??'').trim()!=='')return row[k];}return'';}
function parseAmount(v){if(typeof v==='number')return v;return Number(String(v||'').replace(/\$/g,'').replace(/,/g,'').replace(/%/g,'').trim())||0;}
function parseDate(v){if(!v)return null;if(v instanceof Date)return v;const s=String(v).trim();if(/^\d+(\.\d+)?$/.test(s)){const serial=Number(s);if(serial>20000)return new Date(Math.round((serial-25569)*86400*1000));}let d=new Date(s.replace('a. m.','AM').replace('p. m.','PM').replace('a.m.','AM').replace('p.m.','PM'));if(!isNaN(d))return d;const m=s.match(/(\d{1,2})\/(\d{1,2})\/(\d{4})/);if(m)return new Date(Number(m[3]),Number(m[2])-1,Number(m[1]));return null;}
function iso(d){return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`:'';}function mes(d){return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`:'Sin fecha';}
function jsonp(url,timeout=18000){return new Promise((resolve,reject)=>{const cb='ava_cb_'+Date.now()+'_'+Math.random().toString(36).slice(2);const script=document.createElement('script');const timer=setTimeout(()=>{cleanup();reject(new Error('Tiempo agotado al leer Apps Script'));},timeout);function cleanup(){clearTimeout(timer);delete window[cb];script.remove();}window[cb]=data=>{cleanup();resolve(data);};script.onerror=()=>{cleanup();reject(new Error('No se pudo conectar con Apps Script'));};script.src=url+(url.includes('?')?'&':'?')+'callback='+cb+'&t='+Date.now();document.body.appendChild(script);});}
async function fetchSheet(cfg){const data=await jsonp(`${API_URL}?accion=datos&hoja=${encodeURIComponent(cfg.nombre)}`);if(data.error)throw new Error(data.mensaje||'Apps Script devolvió error');const rows=data.datos||data.data||[];return rows.map(r=>normalizeRow(r,cfg));}
function normalizeRow(row,cfg){const fechaRaw=cfg.tipo==='COBRADO'?getField(row,['Fecha del Viaje','Fecha Viaje','Fecha','Fecha Cobro']):getField(row,['Fecha Corrida','Fecha Sanción','Fecha Recepción Reporte','Fecha']);const fecha=parseDate(fechaRaw);const conductor=getField(row,['Conductor','Operador','Nombre Conductor']);const cajero=cfg.tipo==='COBRADO'?getField(row,['Nombre Cajero','Cajero','Cajero Cobro']):getField(row,['Preceptor','Analista','Nombre Cajero','Cajero']);const monto=cfg.tipo==='COBRADO'?parseAmount(getField(row,['Monto Recuperado','Monto','Importe'])):parseAmount(getField(row,['Por Cobrar','Costo','Monto Adeudo','Adeudo','Monto','Importe']));return{tipo:cfg.tipo,empresa:cfg.empresa,hoja:cfg.nombre,fecha,fechaISO:iso(fecha),mes:mes(fecha),viaje:getField(row,['Viaje','Id Viaje','ID Viaje','Reporte']),conductor,cajero,estatus:cfg.tipo==='COBRADO'?'Cobrado':String(getField(row,['Sanción','Estatus','Status','Tipo'])||'Pendiente'),monto,raw:row};}
async function loadData(){allRows=[];clearCharts();setStatus('Cargando información desde Google Sheet...');let avisos=[];for(const h of HOJAS){try{setStatus('Leyendo pestaña '+h.nombre+'...');const rows=await fetchSheet(h);allRows.push(...rows);}catch(e){console.error(h.nombre,e);avisos.push(h.nombre+': '+e.message);}}allRows=allRows.filter(r=>r.conductor||r.viaje||r.monto>0);populateFilters();applyFilters();if(!allRows.length){setStatus('No se cargaron registros. Actualiza el Apps Script con el código JSONP incluido en este paquete.', 'error');return;}setStatus(`Actualizado: ${num(allRows.length)} registros cargados.${avisos.length?' Avisos: '+avisos.join(' | '):''}`,avisos.length?'warn':'ok');}
function unique(a){return[...new Set(a.map(x=>String(x||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));}function fill(id,vals,label){const s=$(id),cur=s.value;s.innerHTML=`<option value="">${label}</option>`+vals.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('');if(vals.includes(cur))s.value=cur;}
function populateFilters(){fill('cajero',unique(allRows.map(r=>r.cajero)),'Todos');fill('conductor',unique(allRows.map(r=>r.conductor)),'Todos');}
function applyFilters(){const empresa=$('empresa').value,tipo=$('tipo').value,desde=$('desde').value,hasta=$('hasta').value,cajero=$('cajero').value,conductor=$('conductor').value,b=cleanText($('buscar').value);currentRows=allRows.filter(r=>{if(empresa&&r.empresa!==empresa)return false;if(tipo&&r.tipo!==tipo)return false;if(desde&&r.fechaISO&&r.fechaISO<desde)return false;if(hasta&&r.fechaISO&&r.fechaISO>hasta)return false;if(cajero&&r.cajero!==cajero)return false;if(conductor&&r.conductor!==conductor)return false;if(b&&!cleanText([r.tipo,r.empresa,r.fechaISO,r.viaje,r.conductor,r.cajero,r.estatus,r.monto].join(' ')).includes(b))return false;return true;});renderKpis();renderTable();renderCharts();}
function isDebt(r){const s=cleanText(r.estatus);return r.tipo==='ADEUDO'&&!s.includes('cobrado')&&!s.includes('pagado')&&!s.includes('condonado');}function sum(a){return a.reduce((x,r)=>x+Number(r.monto||0),0);}
function renderKpis(){const cob=currentRows.filter(r=>r.tipo==='COBRADO'),ade=currentRows.filter(isDebt),tc=sum(cob),ta=sum(ade),rec=tc+ta?tc/(tc+ta)*100:0;$('totalCobrado').textContent=money(tc);$('movCobrado').textContent=num(cob.length)+' movimientos';$('totalAdeudo').textContent=money(ta);$('movAdeudo').textContent=num(ade.length)+' pendientes';$('recuperacion').textContent=rec.toFixed(1)+'%';$('conductoresAdeudo').textContent=num(unique(ade.map(r=>r.conductor)).length);}
function renderTable(){ $('summary').textContent=num(currentRows.length)+' registros encontrados';$('tbody').innerHTML=currentRows.slice(0,1000).map(r=>`<tr><td><span class="badge ${r.tipo==='COBRADO'?'cobrado':'adeudo'}">${r.tipo}</span></td><td>${r.empresa}</td><td>${r.fechaISO||'<span class="muted">Sin fecha</span>'}</td><td>${escapeHtml(r.viaje)}</td><td>${escapeHtml(r.conductor||'Sin dato')}</td><td>${escapeHtml(r.cajero||'Sin dato')}</td><td>${escapeHtml(r.estatus)}</td><td class="money">${money(r.monto)}</td></tr>`).join('');}
function group(rows,key,limit=12){const m=new Map();rows.forEach(r=>{const n=r[key]||'Sin dato';m.set(n,(m.get(n)||0)+Number(r.monto||0));});return[...m.entries()].map(([name,total])=>({name,total})).sort((a,b)=>b.total-a.total).slice(0,limit);}function palette(n){return Array.from({length:n},(_,i)=>COLORS[i%COLORS.length]);}function short(v){return String(v||'Sin dato').slice(0,32);}
function renderCharts(){if(!window.Chart)return;const cob=currentRows.filter(r=>r.tipo==='COBRADO'),ade=currentRows.filter(isDebt);const empresas=['TRT','SUR'];draw('chartEmpresa','bar',empresas,[{label:'Cobrado',data:empresas.map(e=>sum(cob.filter(r=>r.empresa===e))),backgroundColor:'#16a34a'},{label:'Adeudo',data:empresas.map(e=>sum(ade.filter(r=>r.empresa===e))),backgroundColor:'#dc2626'}]);const meses=unique(currentRows.map(r=>r.mes).filter(x=>x!=='Sin fecha'));draw('chartTendencia','line',meses,[{label:'Cobrado',data:meses.map(m=>sum(cob.filter(r=>r.mes===m))),borderColor:'#16a34a',backgroundColor:'rgba(22,163,74,.15)',fill:true,tension:.35},{label:'Adeudo',data:meses.map(m=>sum(ade.filter(r=>r.mes===m))),borderColor:'#dc2626',backgroundColor:'rgba(220,38,38,.12)',fill:true,tension:.35}]);const caj=group(cob,'cajero');draw('chartCajeros','bar',caj.map(x=>short(x.name)),[{label:'Cobrado',data:caj.map(x=>x.total),backgroundColor:palette(caj.length)}],true);const con=group(ade,'conductor');draw('chartConductores','bar',con.map(x=>short(x.name)),[{label:'Adeudo',data:con.map(x=>x.total),backgroundColor:palette(con.length).reverse()}],true);const est=group(currentRows.filter(r=>r.tipo==='ADEUDO'),'estatus',8);drawDoughnut(est);}
function clearCharts(){Object.values(charts).forEach(c=>c&&c.destroy&&c.destroy());charts={};}
function draw(id,type,labels,datasets,h=false){if(charts[id])charts[id].destroy();charts[id]=new Chart($(id),{type,data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,indexAxis:h?'y':'x',plugins:{legend:{position:'bottom'},tooltip:{callbacks:{label:c=>`${c.dataset.label}: ${money(c.raw)}`}}},scales:{x:{grid:{display:false},ticks:{autoSkip:false,maxRotation:h?0:35}},y:{beginAtZero:true,ticks:{callback:v=>h?v:money(v)}}}}});}
function drawDoughnut(est){const id='chartEstatus';if(charts[id])charts[id].destroy();charts[id]=new Chart($(id),{type:'doughnut',data:{labels:est.map(x=>short(x.name)),datasets:[{data:est.map(x=>x.total),backgroundColor:palette(est.length),borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'},tooltip:{callbacks:{label:c=>`${c.label}: ${money(c.raw)}`}}}}});}
function exportCsv(){const headers=['Tipo','Empresa','Fecha','Viaje','Conductor','Cajero/Preceptor','Estatus','Monto'];const rows=currentRows.map(r=>[r.tipo,r.empresa,r.fechaISO,r.viaje,r.conductor,r.cajero,r.estatus,r.monto]);const csv=[headers,...rows].map(row=>row.map(c=>`"${String(c??'').replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='reporte-ava.csv';a.click();URL.revokeObjectURL(a.href);}
window.addEventListener('DOMContentLoaded',()=>{['empresa','tipo','desde','hasta','cajero','conductor','buscar'].forEach(id=>$(id).addEventListener('input',applyFilters));$('btnRefresh').addEventListener('click',loadData);$('btnExport').addEventListener('click',exportCsv);loadData();});
