/* CIO AVA v46 — panel de administración de usuarios */
let adminUsersCache=[];
const adminEsc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function adminIsReady(){return typeof session!=='undefined'&&session?.token&&session?.rol==='ADMINISTRADOR'}
function adminFormatDate(value){if(!value)return 'Sin acceso';const d=new Date(value);return isNaN(d)?'Sin acceso':d.toLocaleString('es-MX',{dateStyle:'short',timeStyle:'short'})}
function adminDeviceLabel(value){const s=String(value||'No disponible');if(s==='No disponible')return s;let browser='Navegador';if(/Edg\//i.test(s))browser='Microsoft Edge';else if(/Chrome\//i.test(s))browser='Google Chrome';else if(/Firefox\//i.test(s))browser='Mozilla Firefox';else if(/Safari\//i.test(s))browser='Safari';let os='';if(/Windows/i.test(s))os='Windows';else if(/Android/i.test(s))os='Android';else if(/iPhone|iPad/i.test(s))os='iOS';else if(/Macintosh|Mac OS/i.test(s))os='macOS';else if(/Linux/i.test(s))os='Linux';return `${browser}${os?' · '+os:''}`}
function adminSetMessage(text,type=''){const el=document.querySelector('#adminCreateMessage');if(!el)return;el.textContent=text;el.className='admin-form-message '+type}
function adminUpdateKpis(users){const total=users.length,active=users.filter(u=>u.activo).length,admins=users.filter(u=>u.rol==='ADMINISTRADOR').length,logins=users.reduce((a,u)=>a+(Number(u.totalAccesos)||0),0);const set=(id,v)=>{const e=document.querySelector(id);if(e)e.textContent=Number(v).toLocaleString('es-MX')};set('#adminUsersTotal',total);set('#adminUsersActive',active);set('#adminUsersAdmins',admins);set('#adminUsersLogins',logins)}
function adminRenderUsers(){const body=document.querySelector('#adminUsersBody');if(!body)return;const q=(document.querySelector('#adminUsersSearch')?.value||'').toLowerCase();const users=adminUsersCache.filter(u=>[u.usuario,u.nombre,u.rol,u.ultimoEquipo,adminDeviceLabel(u.ultimoEquipo)].join(' ').toLowerCase().includes(q));if(!users.length){body.innerHTML='<tr><td colspan="7" class="admin-empty">No se encontraron usuarios.</td></tr>';return}body.innerHTML=users.map(u=>`<tr class="${u.activo?'':'is-disabled'}">
<td><div class="admin-person"><span>${adminEsc((u.nombre||u.usuario).charAt(0).toUpperCase())}</span><div><b>${adminEsc(u.nombre||u.usuario)}</b><small>${adminEsc(u.usuario)}</small></div></div></td>
<td><span class="role-pill ${u.rol==='ADMINISTRADOR'?'admin':'user'}">${adminEsc(u.rol)}</span></td>
<td><span class="status-pill ${u.activo?'active':'inactive'}">${u.activo?'Activo':'Inactivo'}</span></td>
<td><b class="table-date">${adminEsc(adminFormatDate(u.ultimoAcceso))}</b><small>${u.fechaCreacion?'Creado: '+adminEsc(adminFormatDate(u.fechaCreacion)):'Fecha de creación no registrada'}</small></td>
<td><b>${Number(u.totalAccesos||0).toLocaleString('es-MX')}</b></td>
<td title="${adminEsc(u.ultimoEquipo||'')}"><b>${adminEsc(adminDeviceLabel(u.ultimoEquipo))}</b><small class="device-detail">${adminEsc(u.ultimoEquipo||'No disponible')}</small></td>
<td><div class="admin-actions"><button class="mini-btn" data-admin-action="password" data-user="${adminEsc(u.usuario)}">Contraseña</button><button class="mini-btn ${u.activo?'danger':'success'}" data-admin-action="toggle" data-user="${adminEsc(u.usuario)}" data-active="${u.activo?'true':'false'}">${u.activo?'Desactivar':'Activar'}</button></div></td>
</tr>`).join('')}
async function adminLoadUsers(showToast=false){if(!adminIsReady())return;const body=document.querySelector('#adminUsersBody');if(body)body.innerHTML='<tr><td colspan="7" class="admin-empty">Cargando usuarios…</td></tr>';try{const j=await apiGet('admin_usuarios',{token:session.token});if(j.error)throw new Error(j.mensaje||'No fue posible cargar usuarios.');adminUsersCache=j.usuarios||[];adminUpdateKpis(adminUsersCache);adminRenderUsers();if(showToast&&typeof toast==='function')toast('Usuarios actualizados')}catch(e){console.error(e);if(body)body.innerHTML=`<tr><td colspan="7" class="admin-empty error">${adminEsc(e.message)}</td></tr>`}}
async function adminCreateUser(e){e.preventDefault();if(!adminIsReady())return;const btn=e.submitter||e.target.querySelector('button[type="submit"]'),payload={accion:'admin_crear_usuario',token:session.token,nombre:document.querySelector('#adminNewName').value,usuario:document.querySelector('#adminNewUser').value,contrasena:document.querySelector('#adminNewPassword').value,rol:document.querySelector('#adminNewRole').value};btn.disabled=true;adminSetMessage('Creando usuario…');try{const j=await apiPost(payload);if(j.error)throw new Error(j.mensaje||'No fue posible crear el usuario.');e.target.reset();adminSetMessage(j.mensaje||'Usuario creado.','success');await adminLoadUsers();if(typeof loadLoginUsers==='function')await loadLoginUsers();if(typeof toast==='function')toast('Usuario creado correctamente')}catch(err){adminSetMessage(err.message,'error')}finally{btn.disabled=false}}
async function adminResetPassword(usuario){const nueva=window.prompt(`Nueva contraseña para ${usuario}:`);if(nueva===null)return;if(String(nueva).trim().length<4){alert('La contraseña debe tener al menos 4 caracteres.');return}try{const j=await apiPost({accion:'admin_restaurar_contrasena',token:session.token,usuario,nuevaContrasena:nueva});if(j.error)throw new Error(j.mensaje);if(typeof toast==='function')toast('Contraseña restablecida')}catch(e){alert(e.message||'No fue posible cambiar la contraseña.')}}
async function adminToggleUser(usuario,current){const next=!current;if(!confirm(`${next?'Activar':'Desactivar'} la cuenta ${usuario}?`))return;try{const j=await apiPost({accion:'admin_cambiar_estado',token:session.token,usuario,activo:next});if(j.error)throw new Error(j.mensaje);await adminLoadUsers();if(typeof loadLoginUsers==='function')await loadLoginUsers();if(typeof toast==='function')toast(j.mensaje||'Estado actualizado')}catch(e){alert(e.message||'No fue posible cambiar el estado.')}}
function setupAdminUsers(){document.querySelector('#adminCreateUserForm')?.addEventListener('submit',adminCreateUser);document.querySelector('#adminRefreshUsers')?.addEventListener('click',()=>adminLoadUsers(true));document.querySelector('#adminUsersSearch')?.addEventListener('input',adminRenderUsers);document.querySelector('#adminUsersBody')?.addEventListener('click',e=>{const b=e.target.closest('[data-admin-action]');if(!b)return;if(b.dataset.adminAction==='password')adminResetPassword(b.dataset.user);if(b.dataset.adminAction==='toggle')adminToggleUser(b.dataset.user,b.dataset.active==='true')});document.querySelector('.nav[data-view="usuarios"]')?.addEventListener('click',()=>adminLoadUsers());document.addEventListener('cioava:session-ready',()=>{if(adminIsReady())adminLoadUsers()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setupAdminUsers,{once:true});else setupAdminUsers();
