/* CIO AVA v1.0 — auditoría y navegación institucional */
let auditCache=[];
const auditEsc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function auditSession(){return typeof session!=='undefined'&&session?.token?session:null}
function auditSend(evento,modulo,detalle=''){const s=auditSession();if(!s)return;apiPost({accion:'auditoria',token:s.token,evento,modulo,detalle,equipo:navigator.userAgent}).catch(()=>{});}
function auditFormat(v){if(!v)return '—';const d=new Date(v);return isNaN(d)?'—':d.toLocaleString('es-MX',{dateStyle:'short',timeStyle:'medium'})}
function auditRender(){const body=document.querySelector('#auditBody');if(!body)return;const q=(document.querySelector('#auditSearch')?.value||'').toLowerCase(),act=document.querySelector('#auditAction')?.value||'';const rows=auditCache.filter(r=>(!act||r.accion===act)&&[r.usuario,r.nombre,r.rol,r.accion,r.modulo,r.detalle,r.equipo].join(' ').toLowerCase().includes(q));body.innerHTML=rows.length?rows.map(r=>`<tr><td>${auditEsc(auditFormat(r.fecha))}</td><td><b>${auditEsc(r.nombre||r.usuario)}</b><small>${auditEsc(r.usuario)}</small></td><td>${auditEsc(r.rol)}</td><td><span class="audit-action">${auditEsc(r.accion)}</span></td><td>${auditEsc(r.modulo)}</td><td>${auditEsc(r.detalle||'—')}</td><td title="${auditEsc(r.equipo)}">${auditEsc((r.equipo||'—').slice(0,65))}</td></tr>`).join(''):'<tr><td colspan="7" class="admin-empty">No hay registros que coincidan.</td></tr>'}
async function auditLoad(){const s=auditSession();if(!s||s.rol!=='ADMINISTRADOR')return;const body=document.querySelector('#auditBody');if(body)body.innerHTML='<tr><td colspan="7" class="admin-empty">Cargando auditoría…</td></tr>';try{const j=await apiGet('admin_auditoria',{token:s.token,limite:800});if(j.error)throw new Error(j.mensaje);auditCache=j.registros||[];auditRender()}catch(e){if(body)body.innerHTML=`<tr><td colspan="7" class="admin-empty error">${auditEsc(e.message)}</td></tr>`}}
function setupAudit(){
 document.querySelector('#auditRefresh')?.addEventListener('click',auditLoad);document.querySelector('#auditSearch')?.addEventListener('input',auditRender);document.querySelector('#auditAction')?.addEventListener('change',auditRender);
 document.addEventListener('click',e=>{const nav=e.target.closest('.nav[data-view]');if(nav){const view=nav.dataset.view;auditSend('NAVEGACION',view,nav.textContent.trim());if(view==='auditoria')setTimeout(auditLoad,30)}const exp=e.target.closest('#pdfBtn,#pdfBtn2,#excelBtn,#csvBtn');if(exp)auditSend('EXPORTACION','REPORTES',exp.id.includes('pdf')?'PDF':exp.id.includes('excel')?'EXCEL':'CSV');const a=e.target.closest('#openAssistantBtn,.assistant-question');if(a){document.querySelector('#helpBusBtn')?.click();const q=a.dataset.question;if(q)setTimeout(()=>{const input=document.querySelector('#helpChatInput');if(input){input.value=q;document.querySelector('#helpChatForm')?.requestSubmit()}},150)}});
 document.addEventListener('cioava:session-ready',()=>{if(auditSession()?.rol==='ADMINISTRADOR')auditLoad()});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setupAudit,{once:true});else setupAudit();
